#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: generic
sudo: true

git:
  depth: 1
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - libssl-dev:i386
      - gcc-multilib
env:
  global:
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1525"
    - BYOND_MACRO_COUNT=2
 
cache:
  directories:
    - $HOME/BYOND

script:
    bash scripts/travis_pre_byond.sh

